module.exports = {
    "card_home_title": "While Starting",
    "card_home_desc": "Great Service for a Low Fee! Buy Your Product Now And You Have %var% Service!",
    "card_panel_go": "Go to Panel!",
    "card_login_go": "Login!",
    "card_contact_go": "Telegram Contact",
    "mostsell_title": "Top Selling Products;",
    "mostsell_popular": "POPULAR",
    "mostsell_examine": "Review",
    "mostsell_condition": "Confidentiality Applies. All Rights Reserved.",
    "preferus_title": "Those Who Prefer Us",
    "preferus_desc": "We provide service to our customers who want to catch quality and cheap. This has always been our service philosophy. QUALITY Awaits those who prefer us. Come on, place your order!",
    "preferus_users": "Users",
    "preferus_customer": "Customer",
    "team_title": "Our Team",
    "team_desc": "People Who Contributed to the Project Ensuring the Continuity of the Project!",
    "products_condition": "Confidentiality Applies. All Rights Reserved.",
    "products_notfound": "Product Not Found",
    "changepass_title": "Change Password",
    "changepass_noacc": "I do not have an account",
    "changepass_reg": "Register",
    "changepass_wait_title": "Password Updating!",
    "changepass_wait_desc": "Please Wait Processing..",
    "saveacc_title": "Recover Your Account",
    "saveacc_sendmail": "Send E-Mail",
    "saveacc_noacc": "I do not have an account",
    "saveacc_alert_title": "Check Your E-Mail!",
    "saveacc_alert_desc": "E-Mail / User Name Review Your Mail Account (Can't Be Sent If There Is No Account!)",
    "login_title": "Login!",
    "login_button": "Login!",
    "login_wait_title": "Logging in!",
    "login_wait_desc": "Please Wait Checking Information..",
    "register_title": "Create Account",
    "register_button": "Create Account!",
    "register_noacc": "I do not have an account",
    "register_wait_title": "Creating Record!",
    "register_wait_desc": "Please Wait We are creating your registration..",
    "buy_footer": "No Returns",
    "buy_watch": "Watch Video",
    "buy_block_title": "Item Cannot Be Purchased",
    "buy_block_desc": "Admin Prohibited Buying This Product!",
    "buy_question_title": "Please Fill",
    "buy_question_footer": "Please Make Sure You Enter Correct Information! Canceled / Invalid Return If Entered Incorrectly!",
    "buy_wait_title": "Payment is being made..",
    "buy_wait_desc": "Please Wait..",
    "buy_nomoney_title": "Please Add Balance!",
    "buy_nomoney_desc": "You Don't Have Enough Balance to Buy This Product",
    "buy_nomoney_button": "Quick Add Balance",
    "buy_member_title": "Add the bot!",
    "buy_member_desc": "Please Add The Bot So We Can Send Members To Your Server!",
    "buy_member_button": "Add Bot",
    "buy_member_footer": "Do not kick the bot from the server until the process is complete!",
    "dashboard_tickets_title": "Support Request",
    "dashboard_tickets_replied": "Answered",
    "dashboard_tickets_closed": "It is closed",
    "dashboard_tickets_notfound": "You Have Never Created a Ticket",
    "dashboard_tickets_wait": "Awaiting Answer",
    "dashboard_ticket_title": "Support Request",
    "dashboard_ticket_continuetitle": "Headed Support Request",
    "dashboard_ticket_footer": "Your Account Is Responsible For Every Message You Send.",
    "dashboard_ticket_wait_title": "Processing!",
    "dashboard_ticket_wait_desc": "Please Wait Process In Progress..",
    "dashboard_ticket_create_title": "Create Support Request",
    "dashboard_ticket_create_placeholder": "Specify your problem..",
    "dashboard_ticket_create_button": "Create",
    "dashboard_ticket_create_wait_title": "Processing!",
    "dashboard_ticket_create_wait_desc": "Please Wait Process In Progress..",
    "dashboard_settings_title": "Settings",
    "dashboard_settings_present": "Current Password",
    "dashboard_settings_newpass": "New Password",
    "dashboard_settings_repass": "Password Again",
    "dashboard_settings_button": "Change Password",
    "dashboard_settings_wait_title": "Processing!",
    "dashboard_settings_wait_desc": "Please Wait Process In Progress..",
    "dashboard_orders_title": "My products",
    "dashboard_orders_id": "Id (For Real Id Click)",
    "dashboard_orders_request": "Under Delivery!",
    "dashboard_orders_accept": "Was delivered!",
    "dashboard_orders_reject": "Returned!",
    "dashboard_orders_download": "Delivered, Download Now",
    "dashboard_orders_copy_title": "Successfully, Id Copied",
    "dashboard_orders_copy_desc": "Id Successfully Copied!",
    "dashboard_addmoney_title": "Load Balance",
    "dashboard_addmoney_type": "Payment Type",
    "dashboard_addmoney_footer": "Balance is non-refundable, non-transferable.",
    "dashboard_addmoney_button": "Load",
    "dashboard_addmoney_wait_title": "Processing!",
    "dashboard_addmoney_wait_desc": "Please Wait Process In Progress..",
    "dashboard_addmoney_redirect_title": "Payment is being forwarded..",
    "dashboard_addmoney_redirect_desc": "You are being redirected to the Payment Service. Our Site Cannot Access Your Information!",
    "dashboard_main_title": "Panel",
    "dashboard_main_card1": "Shopping",
    "dashboard_main_card2": "Balance",
    "dashboard_main_card3": "Loaded Money",
    "dashboard_main_history_title": "Payment History",
    "page_badge_balance": "Balance",
    "page_badge_welcome": "Hi, %var%",
    "page_footer_slogan": "Digital Product Shopping Platform",
    "page_footer_gopanel": "Go to Panel",
    "page_footer_gologin": "Login",
    "page_header_gologin": "Login",
    "page_header_gopanel": "Go to Panel",
    "page_header_home": "Home Page",
    "page_header_allproducts": "All Products",
    "page_sidebar_user_panel": "Panel",
    "page_sidebar_user_orders": "My Orders",
    "page_sidebar_user_ticket": "Support Request",
    "page_sidebar_user_product": "Products",
    "page_sidebar_user_addmoney": "Load Balance",
    "page_sidebar_user_settings": "Settings",
    "page_sidebar_user_logout": "Log Out",
    "meta_title_home": "Home Page",
    "meta_desc_home": "Best Service and Quality Guaranteed Platform with Low Fee, Join us and be a part of quality!",
    "meta_title_products": "Buy Product",
    "meta_title_buy": "Buy Product",
    "meta_title_register": "Register",
    "meta_title_login": "Login",
    "meta_title_forgetpass": "I forgot my password",
    "meta_title_resetpass": "Change Password",
    "meta_title_error": "Mistake",
    "meta_title_money": "Virtual POS",
    "meta_title_tickets": "My Support Requests",
    "meta_title_ticketcreate": "Create Support Request",
    "meta_title_ticketread": "Support Request",
    "meta_title_orders": "My Orders",
    "meta_title_settings": "Settings",
    "meta_title_addmoney": "Load Balance",
    "meta_title_dashboard": "Panel",
    "api_meta_shipy_success_title": "Successfully, Payment Completed",
    "api_meta_shipy_success_desc": "Please Review Your Membership Panel!",
    "api_meta_shipy_error_title": "Error Occurred While Making Payment",
    "api_meta_shipy_error_desc": "Please try again.",
    "api_meta_products": "Our %have% Products for Sale. Buy Now!",
    "api_meta_register": "Create Your Account Now Start Shopping!",
    "api_meta_login": "Login to your account now and continue from where you left off! Always Top Quality Selling!",
    "api_meta_forgetpass": "Did you forget your password? No problem, we are always behind you. There Are No Accounts Here!",
    "api_register_code_notfound_title": "Email Verification!",
    "api_register_code_notfound_desc": "Code Not Found!",
    "api_register_code_already_title": "Email Verification!",
    "api_register_code_already_desc": "Email Already Verified!",
    "api_register_code_sucess_title": "Successfully Verified!",
    "api_register_code_sucess_desc": "Email Verified Successfully, You Are Forwarding..",
    "api_forgetpass_notfound_title": "Invalid ID",
    "api_forgetpass_notfound_desc": "Connection No More Or Never Existed!",
    "api_product_notfound": "Product Not Found!",
    "api_order_notfound": "Product Deleted!",
    "api_ticketcreate_title_error_title": "Title Long Or Short!",
    "api_ticketcreate_title_error_desc": "Please Enter a Sufficient Title!",
    "api_ticketcreate_category_error_title": "Category Not Found",
    "api_ticketcreate_category_error_desc": "Please Use Appropriate Category!",
    "api_ticketcreate_message_error_title": "Message Long Or Short!",
    "api_ticketcreate_message_error_desc": "Please Enter a Sufficient Message!",
    "api_ticketcreate_replyreq_title": "No More Tickets Can Be Opened",
    "api_ticketcreate_replyreq_desc": "Please be patient..",
    "api_ticketcreate_success_title": "Successfully Created Ticket",
    "api_ticketcreate_success_desc": "Please Wait for Response..",
    "api_ticketsend_ticket_notfound_title": "No Ticket Found",
    "api_ticketsend_ticket_notfound_desc": "Please Contact Admin!",
    "api_ticketsend_message_error_title": "Message Long Or Short!",
    "api_ticketsend_message_error_desc": "Please Enter a Sufficient Message!",
    "api_ticketsend_replyreq_title": "Please wait for the message to be replied.",
    "api_ticketsend_replyreq_desc": "Multiple Messages Cannot Be Posted!",
    "api_ticketsend_success_title": "Successfully, Message Sent",
    "api_ticketsend_success_desc": "Please Wait for Response..",
    "api_buy_error_notfound_title": "Product Not Found!",
    "api_buy_error_notfound_desc": "The Product Is No Longer Available Or No More!",
    "api_buy_error_maxbuy_title": "The Product Cannot Be Taken Anymore!",
    "api_buy_error_maxbuy_desc": "Max Purchase Amount for This Product Has Been Determined as %var%.",
    "api_buy_error_balance_title": "Please Add Balance!",
    "api_buy_error_balance_desc": "You Don't Have Enough Balance to Buy This Product",
    "api_buy_error_notmatch_title": "Information Wrong!",
    "api_buy_error_notmatch_desc": "Please Enter the Required Information Correctly!",
    "api_buy_success_title": "Product Purchased Successfully!",
    "api_buy_success_desc": "Product Added to Your Membership!",
    "api_buy_sell_apierror": "Failed to Complete Api Connection!",
    "api_buy_control_error_invite_title": "Invite Validation Error!",
    "api_buy_control_error_invite_desc": "Invite Cannot Be Verified!",
    "api_buy_control_error_server_title": "Server Not Found!",
    "api_buy_control_error_server_desc": "Please Enter Invitation Correctly!",
    "api_buy_control_error_bot_title": "Please Add Our Bot!",
    "api_buy_control_error_bot_desc": "Add the bot!",
    "api_buy_control_error_stock_title": "No stock!",
    "api_buy_control_error_stock_desc": "We Don't Have Enough Stock. Please Try Again Later!",
    "api_buy_control_error_title": "Problem Occurred",
    "api_buy_control_error_desc": "System Connection Problem Occurred!",
    "api_buy_control_error_maxmember_title": "Too Many Members!",
    "api_buy_control_error_maxmember_desc": "Total %var% Members Sent to This Server! No More Can Be Posted!",
    "api_buy_control_error_maxboost_title": "Too Many Boosts!",
    "api_buy_control_error_maxboost_desc": "Total %var% Boost Sent to This Server! No More Can Be Posted!",
    "api_addmoney_error_amount_title": "Amount Entered Wrong",
    "api_addmoney_error_amount_desc": "Please Enter in Number Format!",
    "api_addmoney_error_amount2_title": "Quantity Large Or Small",
    "api_addmoney_error_amount2_desc": "Please Enter Amount Between 5-10000₺!",
    "api_addmoney_error_noactive_title": "Payment Not Active",
    "api_addmoney_error_noactive_desc": "Payment System Closed By Administrator!",
    "api_addmoney_error_already_title": "Transaction Already Done!",
    "api_addmoney_error_already_desc": "The Transaction Has Been Processed Before!",
    "api_changepass_error_password_desc": "Please Enter Your Account Password!",
    "api_changepass_error_oldpassword_desc": "Please Enter Your Account Password!",
    "api_changepass_error_newpassword_desc": "Please Enter New Password!",
    "api_changepass_error_repassword_desc": "Please Enter Password Again!",
    "api_changepass_error_norepassword_title": "Wrong again!",
    "api_changepass_error_norepassword_desc": "Please Enter Correct Password Again!",
    "api_changepass_error_entrynewrepassword_title": "More Or Less Character!",
    "api_changepass_error_entrynewrepassword_desc": "Please Enter New Password Correctly!",
    "api_changepass_wrong_oldpassword_title": "Your Password is Wrong!",
    "api_changepass_wrong_oldpassword_desc": "Please Enter Your Password Correctly!",
    "api_changepass_wrong_reoldpassword_title": "Old Password Cannot Be Repeated!",
    "api_changepass_wrong_reoldpassword_desc": "Please Enter Your New Password Differently!",
    "api_changepass_success_title": "The password was changed!",
    "api_changepass_success_desc": "Password Changed Successfully!",
    "api_login_error_already_title": "You Are Already Signed In!",
    "api_login_error_already_desc": "Contact Us If You Think There Is A Problem!",
    "api_login_error_email": "Please Enter Email / Username!",
    "api_login_error_password": "Please Enter Password!",
    "api_login_error_notfound_title": "Account Not Found!",
    "api_login_error_notfound_desc": "Your Email-Username Or Password Is Wrong!",
    "api_login_error_verfreq_title": "Complete Your Registration!",
    "api_login_error_verfreq_desc": "Complete Your Registration With The Link In Your Email!",
    "api_login_success_title": "Successfully Signed In!",
    "api_login_success_desc": "You have successfully logged in, you are being redirected..",
    "api_resetpass_error_password": "Please Enter Password!",
    "api_resetpass_error_repassword": "Please Enter Password Again!",
    "api_resetpass_wrong_repassword_title": "Wrong again!",
    "api_resetpass_wrong_repassword_desc": "Please Enter Correct Password Again!",
    "api_resetpass_wrong_password_title": "More Or Less Character!",
    "api_resetpass_wrong_password_desc": "Please Enter Password Correctly!",
    "api_resetpass_error_notfound_title": "Invalid Key!",
    "api_resetpass_error_notfound_desc": "Key Is No Longer Invalid Or Never Existed!",
    "api_resetpass_error_retry_title": "Old Password Cannot Be Repeated!",
    "api_resetpass_error_retry_desc": "Please Enter Your New Password Differently!",
    "api_resetpass_success_title": "Password Changed Successfully!",
    "api_resetpass_success_desc": "Login! Continue Where You Left Off! You are redirected..",
    "api_register_error_email": "Please Enter Email!",
    "api_register_error_username": "Please Enter Username!",
    "api_register_error_password": "Please Enter Password!",
    "api_register_error_repassword": "Please Enter Password Again!",
    "api_register_wrong_utfusername_title": "Username Incorrect!",
    "api_register_wrong_utfusername_desc": "Please Enter Username Only Lowercase! (utf-8 Invalid.)",
    "api_register_wrong_username_title": "More Or Less Character!",
    "api_register_wrong_username_desc": "Please Enter Correct Username!",
    "api_register_wrong_nousername_title": "This Username Cannot Be Used!",
    "api_register_wrong_nousername_desc": "This Username Has Been Banned By Admin!",
    "api_register_wrong_password_title": "More Or Less Character!",
    "api_register_wrong_password_desc": "Please Enter Password Correctly!",
    "api_register_wrong_repassword_title": "Wrong again!",
    "api_register_wrong_repassword_desc": "Please Enter Correct Password Again!",
    "api_register_already_email_title": "Email Already In Use!",
    "api_register_already_email_desc": "The Email You Entered Is In Use!",
    "api_register_already_username_title": "Username Already In Use!",
    "api_register_already_username_desc": "The Username You Entered Is In Use!",
    "api_register_error_mailsend_title": "Email Not Reached!",
    "api_register_error_mailsend_desc": "Email Failed to Send!",
    "api_register_success_title": "Complete Your Registration!",
    "api_register_success_desc": "Complete Your Registration With The Link In Your Email! (It may take 0-6 minutes)",
    "api_loginreq_title": "Sign in!",
    "api_loginreq_desc": "You must be logged in to interact!",
    "api_usernotfound_title": "User not found",
    "api_usernotfound_desc": "Contact Us If You Think There Is A Problem!",
    "api_anyfield": "All Fields Must Be Filled!",
    "api_noinfo_title": "Contact Us!",
    "api_noinfo_desc": "Please Contact Us!",
    "api_accnotfound_title": "Account Not Found!",
    "api_accnotfound_desc": "Your Account No Longer Or Never Existed!",
    "api_database_title": "Serious Problem!",
    "api_database_desc": "Problem Occurred Connecting Database!",
    "back_home_page": "Back to Homepage!",
    "back_page": "Turn back",
    "search_something": "Search for something..",
    "buy": "Buy",
    "fastlogin": "Quick Login",
    "noreached": "Not Reachable!",
    "email_or_username": "Email / Username",
    "register": "Register",
    "forgetpassword": "I forgot my password",
    "email": "E-mail",
    "username": "User name",
    "password": "Password",
    "repassword": "Password Again",
    "conditions": "Terms And Conditions",
    "accepting": "I agree",
    "cancel": "Cancel",
    "order": "Order",
    "title": "Title",
    "status": "Situation",
    "date": "History",
    "category": "Category",
    "balance": "Balance",
    "order2": "Order",
    "suggestion": "Suggestion",
    "problem": "Problem",
    "product": "Product",
    "products": "Products",
    "price": "Price",
    "amount": "Amount",
    "institutional": "Institutional",
    "shortcut": "Shortcut",
    "software": "Software",
    "all": "All",
    "loading": "Loading..",
    "mesagewait": "Message..",
    "pagenotfound": "Page Not Found!",
    "contact": "Contact"
  }
